PROJECT_NAME_HERE/PROJECT_NAME_HERE/urls.py
from django.urls import path, include, reverse
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.contrib.auth.decorators import login_required

admin.site.login = login_required(admin.site.login)

urlpatterns = [
    path('accounts/', include('apps.accounts.urls', namespace="accounts")),
    path('dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    path("Ww33AVMWvekVt8UhxosX/YzWWxjPVfeI5j8UsJZzP/HL9eMqygOmEK1rQugoqY/2AaA8qIG35cA0dq0PisC/", admin.site.urls),
    path("", include('apps.portal.urls', namespace="portal" )),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

handler404 = 'apps.core.views.page_not_found'
handler500 = 'apps.core.views.server_error'
handler403 = 'apps.core.views.permission_denied'
handler400 = 'apps.core.views.bad_request'

PROJECT_NAME_HERE/apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView, name="login"),
    path('loginas/<int:id>/', LoginAsUserView, name="loginas"),
    path('loginas/logout/', LogoutAsUserView, name="logoutas"),
    path('register/', UserSignupView, name="register"),
    path('logout/', LogoutView, name="logout"),
    path('checkLogin/', isUserLoggedIn, name="check-login"),
    path("forgot-password/", PasswordResetView, name="password_reset"),
    path("forgot-password/validate/<uidb64>/<token>/", PasswordResetTokenValidateView, name="password_reset_confirm"),
    path("register/activate/<uidb64>/<token>/", ActivateAccountTokenValidateView, name="activate-account"),
    path("register/resend-activation/", ResendAccountActivationView, name="resend-account-activation"),
    path('get/users/autocomplete', AutocompleteUsersListView, name="get-autocomplete-users-list"),
]

PROJECT_NAME_HERE/apps/dashboard/urls.py
from . import views as v
from apps.accounts.views import ActivateUser, EnableUser, RemoveUser, \
    SuspendUser
from django.contrib.auth.views import TemplateView
from django.urls import include, path

app_name = "dashboard"

urlpatterns = [
    path("users/browse/", v.BrowseUsersView, name="list-users"),
    path("profile/", v.UserEditView, name="profile"),
    path("settings/", v.ManageSiteView, name="site-management"),
    path("settings/users/manage/new/", v.UserCreationView, name="create-user"),
    path("settings/users/manage/edit/<int:userid>/", v.UserEditView, name="edit-user"),
    path("settings/users/manage/suspend/<int:userid>/", SuspendUser, name="suspend-user"),
    path("settings/users/manage/enable/<int:userid>/", EnableUser, name="enable-user"),
    path("settings/users/manage/remove/<int:userid>/", RemoveUser, name="remove-user"),
    path("settings/users/manage/activate/<int:userid>/", ActivateUser, name="activate-user"),
    path("", v.IndexView, name="home"),
]

PROJECT_NAME_HERE/apps/dashboard/models.py
from django.db import models, IntegrityError

PROJECT_NAME_HERE/apps/dashboard/forms.py
from crispy_forms.bootstrap import InlineRadios
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Layout, Submit

from django import forms
from django.contrib.auth.forms import AdminPasswordChangeForm
from rolepermissions.checkers import has_permission

from apps.accounts.models import User
from apps.core.constants import permissions as p
from apps.accounts.roles import Subscriber, Admin, DemoUser


class UserForm(forms.ModelForm):

    gender = forms.ChoiceField(
        choices=User.gender_choices,
        widget=forms.RadioSelect
    )

    mobile = forms.CharField(
        label="Mobile Number"
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'gender',
                  'avatar', 'mobile']

    def __init__(self, user, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "container"
        self.helper.label_class = "font-weight-bold"
        edit_sensitive_fields = True if has_permission(
            user, p.EDIT_USERS) else False

        emailField = Field('email')

        if not edit_sensitive_fields:
            emailField = Field('email', readonly=edit_sensitive_fields)

        self.helper.layout = Layout(
            Div(
                Field('first_name', wrapper_class='col-12 col-md-6'),
                Field('last_name', wrapper_class='col-12 col-md-6'),
                css_class="row"
            ),
            emailField,
            Field('mobile'),
            InlineRadios('gender'),
            'avatar'
        )
        self.helper.add_input(Submit('user-submit', 'Save'))


class PasswordChangeForm(AdminPasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.pop("autofocus", None)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"

        self.helper.add_input(Submit('password-change', 'Change Password'))


class RolesForm(forms.Form):

    roles = forms.MultipleChoiceField(
        choices=(
            (Subscriber.display_name, Subscriber.title),
            (Admin.display_name, Admin.title),
            (DemoUser.display_name, DemoUser.title)
        )
    )

    def __init__(self, *args, **kwargs):
        super(RolesForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"

        self.helper.add_input(Submit('change-role', 'Save Role(s)'))


class OptionsForm(forms.Form):

    site_title = forms.CharField(label="Site Title", required=False)
    site_description = forms.CharField(
        label="Site Description", required=False)
    support_email = forms.EmailField(label="Support Email", required=False)
    site_url = forms.URLField(label="Site URL", required=True)
    smtp_server = forms.CharField(label="SMTP Server")
    smtp_user = forms.CharField(label="SMPT User")
    smtp_pass = forms.CharField(label="SMTP Password")
    smtp_port = forms.CharField(label="SMTP Port")
    send_mails_as = forms.CharField(max_length=1000, label="Send Email As")

    new_account_email_to_address = forms.EmailField(
        label='New Account Email Notification To')

    def __init__(self, *args, **kwargs):
        super(OptionsForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"

        self.helper.layout = Layout(
            Div(
                'site_title',
                'site_url',
                'site_description',
                'support_email',
                'new_account_email_to_address',
                css_class="card my-3 my-md-5 p-3"
            ),
            Div(
                'smtp_server',
                'smtp_user',
                'smtp_pass',
                'smtp_port',
                'send_mails_as',
                css_class="card my-3 my-md-5 p-3"
            )
        )

        self.helper.add_input(Submit('save-options', 'Save Options'))

PROJECT_NAME_HERE/apps/dashboard/views.py
from datetime import datetime, timedelta

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render, reverse
from django.utils import timezone
from rolepermissions.checkers import has_permission, has_role
from rolepermissions.roles import assign_role, clear_roles, get_user_roles

from apps.accounts import roles as r
from apps.accounts.forms import UserSignupForm
from apps.accounts.models import User
from apps.accounts.roles import Admin, Subscriber
from apps.accounts.utils import DoPostAccountCreation, getTableDataForUsers
from apps.core.constants import database_keys as dk
from apps.core.constants import permissions as p
from apps.core.utils import getOption, getOptions, setOption
from apps.email.models import EmailQueue

from .forms import OptionsForm, PasswordChangeForm, RolesForm, UserForm
from .utils import TableData as td


@login_required
def IndexView(request):

    t = timezone.now()
    if has_role(request.user, Admin) or request.user.is_superuser:
        context = {
            "count": {
                "users": User.objects.all().count(),
                "inactive_users": User.objects.filter(is_active=False).count(),
                "online_users": User.objects.filter(last_active__gte=timezone.now() - timezone.timedelta(seconds=300)).count(),
                "unconfirmed_emails": User.objects.filter(email_confirmed=False).count(),
                "users_joined_this_month": User.objects.filter(date_joined__gte = t.date()-timedelta(t.day)).count(),
                "users_joined_previous_month": User.objects.filter(date_joined__range= [t.date()-timedelta(t.day+30), t.date()-timedelta(t.day)]).count(),
                "users_joined_this_week":User.objects.filter(date_joined__range =[t.date()-timedelta(t.isoweekday()), t.date()]).count(),
                "users_joined_previous_week": User.objects.filter(date_joined__range = [t.date()-timedelta(t.isoweekday()+7), t.date()-timedelta(t.isoweekday())]).count(),
                "users_joined_today": User.objects.filter(date_joined = t.date()).count(),
                "users_joined_yesterday": User.objects.filter(date_joined=t.date()-timedelta(1)).count(),
                "tasks": {
                    "emails": {
                        "pending": EmailQueue.objects.filter(status=EmailQueue.PENDING).count(),
                        "ongoing": EmailQueue.objects.filter(status=EmailQueue.SENDING).count()
                    }
                }
            }
        }
        return render(request, "dashboard/index.html", {"data": context})
    else:
        context = {}
        return render(request, "dashboard/index-subscriber.html", {"data": context})

@login_required
def BrowseUsersView(request):
    if has_permission(request.user, p.READ_USERS):
        enabled_columns = None
        if request.GET.get('enabled_columns', False):
            enabled_columns = request.GET.getlist('enabled_columns')
        sort_by = request.GET.get('sort_by', None)
        sort_order = request.GET.get('sort_order', None)
        search = request.GET.get('search', None)
        page = int(request.GET.get('page', 1))
        page_size = int(request.GET.get('pagesize', 20))

        try:
            tableData = getTableDataForUsers(
                request_obj=request.GET.urlencode(),
                page = page,
                enabled_columns=enabled_columns,
                search=search,
                sort_by=sort_by,
                sort_order=sort_order,
                page_size=page_size,
                admin_view=True
            )
        except td.PageIndexOutOfRangeError:
            raise Http404("Page not found")

        return render(request, "dashboard/list.html", {"tableData": tableData, 'title': "Browse Users"})
    else:
        raise PermissionDenied("You are not allowed to List Users.")


@login_required
def UserEditView(request, userid=None):

    form = None
    user = None
    passForm = None
    rolesForm = None

    if userid == None:
        user = request.user
    elif has_permission(request.user, p.EDIT_USERS) or request.user.id == userid:
        try:
            user = User.objects.get(id=userid)
        except ObjectDoesNotExist as e:
            raise Http404("User Does Not Exist")
    else:
        raise PermissionDenied(
            "You do not have permission to edit/view this user")

    if has_permission(request.user, p.EDIT_USERS):
        roles = []
        for x in get_user_roles(user):
            roles.append(x.display_name)
        rolesForm = RolesForm({'roles': roles})

    form = UserForm(user=request.user, instance=user)
    passForm = PasswordChangeForm(user)

    if request.method == "POST":
        if 'user-submit' in request.POST:
            form = UserForm(user=request.user, data=request.POST or None,
                            files=request.FILES or None, instance=user)
            if form.is_valid():
                form.save()

        if 'password-change' in request.POST:
            passForm = PasswordChangeForm(user, request.POST or None)
            if passForm.is_valid():
                passForm.save()
                update_session_auth_hash(request, user)

        if 'change-role' in request.POST:
            rolesForm = RolesForm(request.POST or None)
            if rolesForm.is_valid():
                user.change_user_role(rolesForm.cleaned_data['roles'])

    return render(request, "dashboard/edit-user.html", {'form': form, 'user_context': user, 'passform': passForm, 'rolesForm': rolesForm})

@login_required
def UserCreationView(request):

    if not has_role(request.user, Admin) and not request.user.is_superuser:
        raise PermissionDenied("You do not have permissions to acess this page!")

    form = None
    if request.method == "POST":
        form = UserSignupForm(data=request.POST or None, files=request.FILES or None, is_admin=True)
        if form.is_valid():
            user = form.save()
            DoPostAccountCreation(user)
            return redirect(reverse('dashboard:list-users'))
    else:
        form = UserSignupForm(is_admin=True)

    return render(request, 'dashboard/form.html', {'form': form, 'title': 'Create New User'})

@login_required
def ManageSiteView(request):
    if not request.user.is_superuser:
        raise PermissionDenied(
            "You do not have permissions to access this page!")

    form = None
    if request.method == "POST":
        form = OptionsForm(data = request.POST, files = request.FILES or None)
        if form.is_valid():
            for data in form.cleaned_data:
                setOption(data, form.cleaned_data[data])
    else:
        form = OptionsForm(initial=getOptions())
    return render(request, "dashboard/settings.html", {"form": form})

PROJECT_NAME_HERE/apps/dashboard/templates/dashboard/components/_footer.html
<footer class="footer">
  <div class="container">
    <div class="row align-items-center flex-row-reverse">
      <div class="col-auto mx-auto mr-md-0">
        <div class="row align-items-center">
          <div class="col-auto">
            v{{ meta.application_version }}&nbsp;
            <a href="mailto:{{ meta.support_email|default:"support@theletstream.com" }}" class="btn btn-outline-primary btn-sm">Contact Support</a>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
        Copyright © 2018
        <a href=".">{{ meta.site_title|default:"Letstream" }}</a>. All rights reserved. Powered by <a href="https://www.theletstream.com/" target="_blank">Letstream</a>.
      </div>
    </div>
  </div>
</footer>

PROJECT_NAME_HERE/apps/dashboard/templates/dashboard/components/_header.html
{% load static %}
{% load core_filters %}
<div class="container-fluid p-0 m-0">
    <div class="row sticky-top">
        <div class="col-12">
            <div class="header card mt-0 mx-auto d-lg-flex p-0" id="main-header">
                <div class="d-flex pl-1 pr-2 py-3 align-items-center">
                    <div class="row w-100">
                        <div class="col-12 col-md-6">
                            <div class="d-flex align-items-center">
                                <span class="avatar mr-3" style="background-image: url('{% static 'assets/images/avatar.png' %}')"></span>
                                <div>
                                    <h5 class="m-0">User Preference</h5>
                                    <small class="text-muted">Extra Info here</small>
                                </div>
                                <div class="ml-3">
                                    <a href="#" class="btn btn-sm btn-outline-secondary">Change</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 fin-year">
                            <div class="row">
                                <small class="text-muted col-6 col-md-12">
                                    <strong class="text-dark">User Preference: </strong>
                                    Not Chosen 
                                    <a href="#" class="text-default"><i class="fe fe-edit"></i></a>
                                </small>
                                <small class="text-muted col-6 col-md-12">
                                    <strong class="text-dark">Mode: </strong>
                                    Not Chosen 
                                    <a href="#" class="text-default"><i class="fe fe-edit"></i></a>    
                                </small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>  

PROJECT_NAME_HERE/apps/dashboard/templates/dashboard/components/_sidebar.html
{% load static %}
<nav id="sidebar" class="sidebar-wrapper bg-dark text-light">
    <div class="sidebar-content">
        <div class="sidebar-brand bg-light text-dark box-shadow-light d-none">
            <a href="{% url 'dashboard:home' %}'">
                <img src="{% static 'assets/images/logo.png' %}" class="header-brand-img" alt="logo">
            </a>
        </div>
        
        <div class="sidebar-header">
            <div class="user-pic">
                <span class="avatar avatar-lg" style="background-image: url('{% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'assets/images/avatar.png' %}{% endif %}')"></span>            
            </div>
            <div class="user-info">
                <span class="user-name">{{ user.first_name|default:'Visitor' }}
                    <strong>{{ user.last_name|default:'' }}</strong>
                </span>
                <span class="user-role">
                    {% if user_roles %}
                        {% for role in user_roles %}{{ role|capfirst }}{% if not forloop.last %},{% endif %} {% endfor %}
                    {% else %}
                        Visitor
                    {% endif %}
                </span>
                <span class="user-status">
                    <i class="fa fa-circle {% if not user.is_online %}text-danger{% endif %}"></i>
                    <span>{% if user.is_online %}Online{% else %}Offline{% endif %}</span>
                </span>
            </div>
        </div>
        <div class="sidebar-menu">
            <ul>
                <li class="sidebar-dropdown">
                    <a href="#">
                        <i class="fa fa-tachometer"></i>
                        <span>Dashboard</span>
                    </a>
                    <span class="dropdown-icon fa fa-sort-desc"></span>
                    <div class="sidebar-submenu">
                        <ul>
                            <li>
                                <a href="{% url 'dashboard:home' %}">Home</a>
                            </li>
                        </ul>
                    </div>
                </li>
                {% if user_roles %}
                {% if "admin" in user_roles|lower %}
                <li class="sidebar-dropdown">
                  <a href="#">
                    <i class="fe fe-user"></i>
                    <span>Admin</span>
                  </a>
                  <span class="dropdown-icon fa fa-sort-desc"></span>
                    <div class="sidebar-submenu">
                      <ul>                    
                        <div class="pt-3 px-2 font-weight-bold text-dark"><i class="fe fe-user"></i> Users Manager</div>
                        <li>
                          <a href="{% url 'dashboard:list-users' %}">Browse</a>
                        </li>
                        <li>
                          <a href="{% url 'dashboard:create-user' %}">Create User</a>
                        </li>

                        {% if user.is_superuser %}
                        <div class="dropdown-divider"></div>
                        <li>
                          <a href="{% url 'dashboard:site-management' %}">
                            <i class="fe fe-settings"></i> Settings
                          </a>
                        </li>
                        {% endif %}
                      </ul>
                    </div>
                {% endif %}
                {% endif %}
                            
                </li>
                <li class="sidebar-dropdown">
                    <a href="#" class="toggle-sidebar px-3 text-center single">
                        <i class="fa fa-chevron-left toggle-icon"></i>
                    </a>
                </li>
            </ul>
        </div>
        <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
        <a href="{% url 'accounts:logout' %}" title="Logout">
            <i class="fa fa-power-off"></i>
        </a>
    </div>
</nav>