PROJECT_NAME_HERE/PROJECT_NAME_HERE/urls.py
from django.urls import path, include, reverse
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.contrib.auth.decorators import login_required

admin.site.login = login_required(admin.site.login)

urlpatterns = [
    path('accounts/', include('apps.accounts.urls', namespace="accounts")),
    path('dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    path("Ww33AVMWvekVt8UhxosX/YzWWxjPVfeI5j8UsJZzP/HL9eMqygOmEK1rQugoqY/2AaA8qIG35cA0dq0PisC/", admin.site.urls),
    path("", include('apps.portal.urls', namespace="portal" )),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

handler404 = 'apps.core.views.page_not_found'
handler500 = 'apps.core.views.server_error'
handler403 = 'apps.core.views.permission_denied'
handler400 = 'apps.core.views.bad_request'

PROJECT_NAME_HERE/apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView, name="login"),
    path('loginas/<int:id>/', LoginAsUserView, name="loginas"),
    path('loginas/logout/', LogoutAsUserView, name="logoutas"),
    path('register/', UserSignupView, name="register"),
    path('logout/', LogoutView, name="logout"),
    path('checkLogin/', isUserLoggedIn, name="check-login"),
    path("forgot-password/", PasswordResetView, name="password_reset"),
    path("forgot-password/validate/<uidb64>/<token>/", PasswordResetTokenValidateView, name="password_reset_confirm"),
    path("register/activate/<uidb64>/<token>/", ActivateAccountTokenValidateView, name="activate-account"),
    path("register/resend-activation/", ResendAccountActivationView, name="resend-account-activation"),
    path('get/users/autocomplete', AutocompleteUsersListView, name="get-autocomplete-users-list"),
]

PROJECT_NAME_HERE/apps/dashboard/urls.py
from . import views as v
from apps.accounts.views import ActivateUser, EnableUser, RemoveUser, \
    SuspendUser
from django.contrib.auth.views import TemplateView
from django.urls import include, path

app_name = "dashboard"

urlpatterns = [
    path("users/browse/", v.BrowseUsersView, name="list-users"),
    path("profile/", v.UserEditView, name="profile"),
    path("settings/", v.ManageSiteView, name="site-management"),
    path("settings/users/manage/new/", v.UserCreationView, name="create-user"),
    path("settings/users/manage/edit/<int:userid>/", v.UserEditView, name="edit-user"),
    path("settings/users/manage/suspend/<int:userid>/", SuspendUser, name="suspend-user"),
    path("settings/users/manage/enable/<int:userid>/", EnableUser, name="enable-user"),
    path("settings/users/manage/remove/<int:userid>/", RemoveUser, name="remove-user"),
    path("settings/users/manage/activate/<int:userid>/", ActivateUser, name="activate-user"),
    path("", v.IndexView, name="home"),
]

PROJECT_NAME_HERE/apps/dashboard/models.py
from django.db import models, IntegrityError

PROJECT_NAME_HERE/apps/dashboard/forms.py
from crispy_forms.bootstrap import InlineRadios
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Layout, Submit

from django import forms
from django.contrib.auth.forms import AdminPasswordChangeForm
from rolepermissions.checkers import has_permission

from apps.accounts.models import User
from apps.core.constants import permissions as p
from apps.accounts.roles import Subscriber, Admin, DemoUser


class UserForm(forms.ModelForm):

    gender = forms.ChoiceField(
        choices=User.gender_choices,
        widget=forms.RadioSelect
    )

    mobile = forms.CharField(
        label="Mobile Number"
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'gender',
                  'avatar', 'mobile']

    def __init__(self, user, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "container"
        self.helper.label_class = "font-weight-bold"
        edit_sensitive_fields = True if has_permission(
            user, p.EDIT_USERS) else False

        emailField = Field('email')

        if not edit_sensitive_fields:
            emailField = Field('email', readonly=edit_sensitive_fields)

        self.helper.layout = Layout(
            Div(
                Field('first_name', wrapper_class='col-12 col-md-6'),
                Field('last_name', wrapper_class='col-12 col-md-6'),
                css_class="row"
            ),
            emailField,
            Field('mobile'),
            InlineRadios('gender'),
            'avatar'
        )
        self.helper.add_input(Submit('user-submit', 'Save'))


class PasswordChangeForm(AdminPasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.pop("autofocus", None)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"

        self.helper.add_input(Submit('password-change', 'Change Password'))


class RolesForm(forms.Form):

    roles = forms.MultipleChoiceField(
        choices=(
            (Subscriber.display_name, Subscriber.title),
            (Admin.display_name, Admin.title),
            (DemoUser.display_name, DemoUser.title)
        )
    )

    def __init__(self, *args, **kwargs):
        super(RolesForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"

        self.helper.add_input(Submit('change-role', 'Save Role(s)'))


class OptionsForm(forms.Form):

    site_title = forms.CharField(label="Site Title", required=False)
    site_description = forms.CharField(
        label="Site Description", required=False)
    support_email = forms.EmailField(label="Support Email", required=False)
    site_url = forms.URLField(label="Site URL", required=True)
    smtp_server = forms.CharField(label="SMTP Server")
    smtp_user = forms.CharField(label="SMPT User")
    smtp_pass = forms.CharField(label="SMTP Password")
    smtp_port = forms.CharField(label="SMTP Port")
    send_mails_as = forms.CharField(max_length=1000, label="Send Email As")

    new_account_email_to_address = forms.EmailField(
        label='New Account Email Notification To')

    def __init__(self, *args, **kwargs):
        super(OptionsForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"

        self.helper.layout = Layout(
            Div(
                'site_title',
                'site_url',
                'site_description',
                'support_email',
                'new_account_email_to_address',
                css_class="card my-3 my-md-5 p-3"
            ),
            Div(
                'smtp_server',
                'smtp_user',
                'smtp_pass',
                'smtp_port',
                'send_mails_as',
                css_class="card my-3 my-md-5 p-3"
            )
        )

        self.helper.add_input(Submit('save-options', 'Save Options'))

PROJECT_NAME_HERE/apps/dashboard/views.py
from datetime import datetime, timedelta

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render, reverse
from django.utils import timezone
from rolepermissions.checkers import has_permission, has_role
from rolepermissions.roles import assign_role, clear_roles, get_user_roles

from apps.accounts import roles as r
from apps.accounts.forms import UserSignupForm
from apps.accounts.models import User
from apps.accounts.roles import Admin, Subscriber
from apps.accounts.utils import DoPostAccountCreation, getTableDataForUsers
from apps.core.constants import database_keys as dk
from apps.core.constants import permissions as p
from apps.core.utils import getOption, getOptions, setOption
from apps.email.models import EmailQueue

from .forms import OptionsForm, PasswordChangeForm, RolesForm, UserForm
from .utils import TableData as td


@login_required
def IndexView(request):

    t = timezone.now()
    if has_role(request.user, Admin) or request.user.is_superuser:
        context = {
            "count": {
                "users": User.objects.all().count(),
                "inactive_users": User.objects.filter(is_active=False).count(),
                "online_users": User.objects.filter(last_active__gte=timezone.now() - timezone.timedelta(seconds=300)).count(),
                "unconfirmed_emails": User.objects.filter(email_confirmed=False).count(),
                "users_joined_this_month": User.objects.filter(date_joined__gte = t.date()-timedelta(t.day)).count(),
                "users_joined_previous_month": User.objects.filter(date_joined__range= [t.date()-timedelta(t.day+30), t.date()-timedelta(t.day)]).count(),
                "users_joined_this_week":User.objects.filter(date_joined__range =[t.date()-timedelta(t.isoweekday()), t.date()]).count(),
                "users_joined_previous_week": User.objects.filter(date_joined__range = [t.date()-timedelta(t.isoweekday()+7), t.date()-timedelta(t.isoweekday())]).count(),
                "users_joined_today": User.objects.filter(date_joined = t.date()).count(),
                "users_joined_yesterday": User.objects.filter(date_joined=t.date()-timedelta(1)).count(),
                "tasks": {
                    "emails": {
                        "pending": EmailQueue.objects.filter(status=EmailQueue.PENDING).count(),
                        "ongoing": EmailQueue.objects.filter(status=EmailQueue.SENDING).count()
                    }
                }
            }
        }
        return render(request, "dashboard/index.html", {"data": context})
    else:
        context = {}
        return render(request, "dashboard/index-subscriber.html", {"data": context})

@login_required
def BrowseUsersView(request):
    if has_permission(request.user, p.READ_USERS):
        enabled_columns = None
        if request.GET.get('enabled_columns', False):
            enabled_columns = request.GET.getlist('enabled_columns')
        sort_by = request.GET.get('sort_by', None)
        sort_order = request.GET.get('sort_order', None)
        search = request.GET.get('search', None)
        page = int(request.GET.get('page', 1))
        page_size = int(request.GET.get('pagesize', 20))

        try:
            tableData = getTableDataForUsers(
                request_obj=request.GET.urlencode(),
                page = page,
                enabled_columns=enabled_columns,
                search=search,
                sort_by=sort_by,
                sort_order=sort_order,
                page_size=page_size,
                admin_view=True
            )
        except td.PageIndexOutOfRangeError:
            raise Http404("Page not found")

        return render(request, "dashboard/list.html", {"tableData": tableData, 'title': "Browse Users"})
    else:
        raise PermissionDenied("You are not allowed to List Users.")


@login_required
def UserEditView(request, userid=None):

    form = None
    user = None
    passForm = None
    rolesForm = None

    if userid == None:
        user = request.user
    elif has_permission(request.user, p.EDIT_USERS) or request.user.id == userid:
        try:
            user = User.objects.get(id=userid)
        except ObjectDoesNotExist as e:
            raise Http404("User Does Not Exist")
    else:
        raise PermissionDenied(
            "You do not have permission to edit/view this user")

    if has_permission(request.user, p.EDIT_USERS):
        roles = []
        for x in get_user_roles(user):
            roles.append(x.display_name)
        rolesForm = RolesForm({'roles': roles})

    form = UserForm(user=request.user, instance=user)
    passForm = PasswordChangeForm(user)

    if request.method == "POST":
        if 'user-submit' in request.POST:
            form = UserForm(user=request.user, data=request.POST or None,
                            files=request.FILES or None, instance=user)
            if form.is_valid():
                form.save()

        if 'password-change' in request.POST:
            passForm = PasswordChangeForm(user, request.POST or None)
            if passForm.is_valid():
                passForm.save()
                update_session_auth_hash(request, user)

        if 'change-role' in request.POST:
            rolesForm = RolesForm(request.POST or None)
            if rolesForm.is_valid():
                user.change_user_role(rolesForm.cleaned_data['roles'])

    return render(request, "dashboard/edit-user.html", {'form': form, 'user_context': user, 'passform': passForm, 'rolesForm': rolesForm})

@login_required
def UserCreationView(request):

    if not has_role(request.user, Admin) and not request.user.is_superuser:
        raise PermissionDenied("You do not have permissions to acess this page!")

    form = None
    if request.method == "POST":
        form = UserSignupForm(data=request.POST or None, files=request.FILES or None, is_admin=True)
        if form.is_valid():
            user = form.save()
            DoPostAccountCreation(user)
            return redirect(reverse('dashboard:list-users'))
    else:
        form = UserSignupForm(is_admin=True)

    return render(request, 'dashboard/form.html', {'form': form, 'title': 'Create New User'})

@login_required
def ManageSiteView(request):
    if not request.user.is_superuser:
        raise PermissionDenied(
            "You do not have permissions to access this page!")

    form = None
    if request.method == "POST":
        form = OptionsForm(data = request.POST, files = request.FILES or None)
        if form.is_valid():
            for data in form.cleaned_data:
                setOption(data, form.cleaned_data[data])
    else:
        form = OptionsForm(initial=getOptions())
    return render(request, "dashboard/settings.html", {"form": form})

PROJECT_NAME_HERE/apps/dashboard/templates/dashboard/_base.html
{% extends '_base.html' %}
{% block title %}{% endblock %}

{% block page %}
      <div class="page-main w-100 toggled">
        {% include 'dashboard/components/_sidebar.html' %}
        <div id="content">
            {% include "dashboard/components/_header.html" %}
            <div class="px-2" style="margin-bottom: 80px;">
            {% block content %}
            {% endblock %}
            </div>
            {% include "dashboard/components/_footer.html" %}
        </div>        
      </div>
{% endblock %}

PROJECT_NAME_HERE/apps/dashboard/templates/dashboard/_base_left_sidebar.html
{% extends 'dashboard/_base.html' %}

{% block content %}
{% block full_content_block %}{% endblock %}
      <div class="mt-1">
        <div class="{% block container_class %}container{% endblock %}">
          <div class="row flex-column-reverse flex-lg-row">
            <div class="col-lg-4 sidebar" style="position: relative;">
              {% block sidebar %}{% endblock %}
            </div>
            <div class="col-lg-8">
              {% block content_block %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
{% block full_content_block_footer %}{% endblock %}
{% endblock %}

PROJECT_NAME_HERE/apps/dashboard/templates/dashboard/edit-user.html
{% extends 'dashboard/_base.html' %}
{% load crispy_forms_tags %}
{% load permission_tags %}
{% load static %}

{% block title %}Edit User{% endblock %}

{% block header_js %}
{{ form.media }}
{% endblock %}

{% block content %}
    <div class="my-3 my-md-5">
        <div class="card w-75 mx-auto">
            <div class="card-header">
                Edit User
            </div>
            <div class="card-body">
                <div class="container">
                    <div class="row">
                        <div class="col-5 mx-auto text-center">
                            <span class="avatar avatar-xxl" style="background-image:url('{% if user_context.avatar %}{{ user_context.avatar.url }}{% else %}{% static 'assets/images/avatar.png' %}{% endif %}')"></span>
                        </div>
                    </div>
                    {% if user|can:constants.permissions.EDIT_USERS %}
                    <div class="row">
                        <fieldset class="form-fieldset w-100 my-3">
                            <div class="form-row align-items-center">
                                <div class="col-12 col-sm-6 form-group align-items-center">
                                    <label class="form-label">User Id</label>
                                    <div class="form-control-plaintext">{{ user_context.id }} {% if user_context.is_active %}(Active){% else %}(Inactive){% endif %}</div>
                                </div>
                                <div class="col-12 col-sm-6 align-items-center">
                                    <label class="form-label">Member Since</label>
                                    <div class="form-control-plaintext">{{ user_context.date_joined }}</div>
                                </div>
                                <div class="col-12 col-sm-6 align-items-center">
                                    <label class="form-label">Last Login</label>
                                    <div class="form-control-plaintext">{{ user_context.last_login }}</div>
                                </div>
                                <div class="col-12 col-sm-6 align-items-center">
                                    <label class="form-label">Email Confirmed</label>
                                    <div class="form-control-plaintext">{{ user_context.email_confirmed }}</div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    {% endif %}
                    <div class="row">
                        <fieldset class="form-fieldset w-100 my-3">
                            {% crispy form form.helper %}
                        </fieldset>
                    </div>
                    <div class="row">
                        <fieldset class="form-fieldset w-100">
                            {% crispy passform %}
                        </fieldset>
                    </div>
                    {% if rolesForm is not None %}
                    <div class="row">
                        <fieldset class="form-fieldset w-100">
                            {% crispy rolesForm %}
                        </fieldset>
                    </div>
                    {% endif %}
                    {% if user|can:constants.permissions.SUSPEND_USERS %}
                    <div class="row">
                        <fieldset class="form-fieldset w-100">
                                {% if user_context.is_active %}
                                <a href="{% if user == user_context %}#{% else %}{% url 'dashboard:suspend-user' user_context.id %}?next={{ request.path }}{% endif %}"><button class="btn btn-danger" {% if user == user_context %}disabled{% endif %}>Suspend Login</button></a>
                                {% else %}
                                <a href="{% url 'dashboard:enable-user' user_context.id %}?next={{ request.path }}"><button class="btn btn-primary">Enable Login</button></a>
                                {% endif %}
                                <a href="{% if user == user_context %}#{% else %}{% url 'dashboard:remove-user' user_context.id %}{% endif %}"><button class="btn btn-danger" {% if user == user_context %}disabled{% endif %}>Remove User</button></a>
                                {% if not user_context.email_confirmed %}
                                <a href="{% url 'dashboard:activate-user' user_context.id %}"><button class="btn btn-warning">Mark email as Confirmed</button></a>
                                {% endif %}
                        </fieldset>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

PROJECT_NAME_HERE/apps/dashboard/templates/dashboard/form.html
{% extends 'dashboard/_base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ title|default:"Untitled Page" }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 card">
                <div class="card-header">
                    <h3 class="card-title">{{ title|default:"Untitled Form" }}</h3>
                </div>
                <div class="card-body">
                    {% crispy form %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

PROJECT_NAME_HERE/apps/dashboard/templates/dashboard/index-subscriber.html
{% extends "dashboard/_base.html" %}
{% load core_filters %}

{% block title %}Home | Dashboard{% endblock %}
{% block content %}
<div class="my-3 my-md-5">
  <div class="container">
    <div class="page-header">
      <h1 class="page-title">
        Dashboard
      </h1>
    </div>
  </div>
</div>
{% endblock %}

PROJECT_NAME_HERE/apps/dashboard/templates/dashboard/index.html
{% extends "dashboard/_base.html" %}
{% load core_filters %}

{% block title %}Home | Dashboard{% endblock %}
{% block content %}
<div class="my-3 my-md-5">
  <div class="container">
    <div class="page-header">
      <h1 class="page-title">
        Quick Access
      </h1>
    </div>
    <div class="row row-cards button-cards">
      <div class="col-6 col-sm-3">
        <div class="card">
          <a href="{% url 'dashboard:list-users' %}" class="btn btn-dark" style="font-size: 1.2em;">
            <div class="card-body p-3 text-center">
              <span class="fe fe-user"></span> Users
            </div>
          </a>
        </div>
      </div>
      <div class="col-6 col-sm-3">
        <div class="card">
          <a href="#" class="btn btn-dark" style="font-size: 1.2em;">
            <div class="card-body p-3 text-center">
              <span class="fe fe-server"></span> Settings
            </div>
          </a>
        </div>
      </div>
      <div class="col-6 col-sm-3">
        <div class="card">
          <a href="{% url 'accounts:logout' %}" class="btn btn-dark" style="font-size: 1.2em;">
            <div class="card-body p-3 text-center">
              <span class="fe fe-log-out"></span> Logout
            </div>
          </a>
        </div>
      </div>
    </div>
    <div class="page-header">
      <h1 class="page-title">
        Dashboard
      </h1>
    </div>
    <div class="row row-cards align-items-center">
      <div class="container">
        <div class="h3 m-2">User Stats</div>
        <div class="row m-2">
          <div class="col-md-4">
            <div class="card">
              <div class="card-body p-3 text-center mx-2">
                <div class="text-right text-green">{{ data.count.online_users|default:0 }} Online</div>
                <div class="h1 m-0">{{ data.count.users|default:"Error" }}</div>
                <div class="text-muted mb-4">Registered Users</div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card">
              <div class="card-body p-3 text-center mx-2">
                <div class="h1 m-0">{{ data.count.inactive_users }}</div>
                <div class="text-muted mb-4">Inactive Users</div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card">
              <div class="card-body p-3 text-center mx-2">
                <div class="h1 m-0">{{ data.count.unconfirmed_emails|default:"Error" }}</div>
                <div class="text-muted mb-4">Unconfirmed Emails</div>
              </div>
            </div>
          </div>
        </div>

        <div class="row m-2">
          <div class="col-md-4">
            <div class="card">
              <div class="card-body p-3 text-center mx-2">
                <div class="h1 m-0">{{ data.count.users_joined_this_month|default:"0" }}</div>
                <div class="text-muted mb-4">Users joined this month</div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card">
              <div class="card-body p-3 text-center mx-2">
                <div class="h1 m-0">{{ data.count.users_joined_this_week|default:"0" }}</div>
                <div class="text-muted mb-4">Users joined this week</div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card">
              <div class="card-body p-3 text-center mx-2">
                <div class="h1 m-0">{{ data.count.users_joined_today|default:"0" }}</div>
                <div class="text-muted mb-4">Users joined today</div>
              </div>
            </div>
          </div>
        </div>

        <div class="row m-2">
          <div class="col-md-4">
            <div class="card">
              <div class="card-body p-3 text-center mx-2">
                <div class="h1 m-0">{{ data.count.users_joined_previous_month|default:"0" }}</div>
                <div class="text-muted mb-4">Users joined last month</div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card">
              <div class="card-body p-3 text-center mx-2">
                <div class="h1 m-0">{{ data.count.users_joined_previous_week|default:"0" }}</div>
                <div class="text-muted mb-4">Users joined last week</div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card">
              <div class="card-body p-3 text-center mx-2">
                <div class="h1 m-0">{{ data.count.users_joined_yesterday|default:"0" }}</div>
                <div class="text-muted mb-4">Users joined yesterday</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="page-header">
      <h1 class="page-title">Background Processes</h1>
    </div>
    <div class="row row-cards align-items-center">
      <div class="col-6 col-sm-3">
        <div class="card bg-dark">
          <div class="card-body">
            <div class="h3 text-center text-white">Email Queue</div>
            <div class="h1 m-0 text-center text-white">{{ data.count.tasks.emails.pending|default:0 }}</div>
            <div class="text-muted mb-3 text-center">Pending</div>
            <div class="text-white text-center">({{ data.count.tasks.emails.ongoing|default:0 }} Ongoing)</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

PROJECT_NAME_HERE/apps/dashboard/templates/dashboard/list-single.html
{% extends 'dashboard/_base.html' %}

{% block title %}{{ title|default:"Untitled Page" }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="my-3 my-md-5">
            {% if title %}
            <div class="card mt-3">
                <div class="card-header">
                    <h3 class="card-title">{{ title }}</h3>
                </div>
            </div>
            {% endif %}
            <div class="row">
                {% if not tableData.meta.disable_search %}
                <div class="col-12">
                    <form class="row">
                        <div class="col-12 {% if tableData.meta.filter %}col-md-6{% endif %}">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Type to search.." name="search" value="{{ tableData.meta.search }}">
                                <span class="input-group-append">
                                    <span class="input-group-btn"><button class="btn btn-primary" type="submit"><i class="fe fe-search"></i></button></span>
                                </span>
                            </div>
                        </div>
                        {% if tableData.meta.filter %}
                        <div class="col-12 col-md-6">
                            <div class="input-group">
                                <select class="form-control" name="filter">
                                    <option value="">Filter By </option>
                                    {% for option in tableData.meta.filter %}
                                    <option value="{{ option.value }}" {% if option.value == tableData.meta.filter_by %}selected{% endif %}>{{ option.label }}</option>
                                    {% endfor %}
                                </select>
                                <span class="input-group-append">
                                    <span class="input-group-btn"><button class="btn btn-warning" type="submit"><i class="fe fe-filter"></i></button></span>
                                </span>
                            </div>
                        </div>
                        {% endif %}
                    </form>
                </div>
                {% endif %}
                <div class="col-12 my-3 my-md-5">
                    {% include 'dashboard/_list-table.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

PROJECT_NAME_HERE/apps/dashboard/templates/dashboard/settings.html
{% extends 'dashboard/_base.html' %}
{% load crispy_forms_tags %}
{% block title %}Settings{% endblock %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h3 class="page-title"><i class="fe fe-settings"></i> Settings</h3>
    </div>
    {% crispy form %}
</div>
{% endblock %}