PROJECT_NAME_HERE/PROJECT_NAME_HERE/urls.py
from django.urls import path, include, reverse
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.contrib.auth.decorators import login_required

admin.site.login = login_required(admin.site.login)

urlpatterns = [
    path('accounts/', include('apps.accounts.urls', namespace="accounts")),
    path('dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    path("Ww33AVMWvekVt8UhxosX/YzWWxjPVfeI5j8UsJZzP/HL9eMqygOmEK1rQugoqY/2AaA8qIG35cA0dq0PisC/", admin.site.urls),
    path("", include('apps.portal.urls', namespace="portal" )),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

handler404 = 'apps.core.views.page_not_found'
handler500 = 'apps.core.views.server_error'
handler403 = 'apps.core.views.permission_denied'
handler400 = 'apps.core.views.bad_request'

PROJECT_NAME_HERE/apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView, name="login"),
    path('loginas/<int:id>/', LoginAsUserView, name="loginas"),
    path('loginas/logout/', LogoutAsUserView, name="logoutas"),
    path('register/', UserSignupView, name="register"),
    path('logout/', LogoutView, name="logout"),
    path('checkLogin/', isUserLoggedIn, name="check-login"),
    path("forgot-password/", PasswordResetView, name="password_reset"),
    path("forgot-password/validate/<uidb64>/<token>/", PasswordResetTokenValidateView, name="password_reset_confirm"),
    path("register/activate/<uidb64>/<token>/", ActivateAccountTokenValidateView, name="activate-account"),
    path("register/resend-activation/", ResendAccountActivationView, name="resend-account-activation"),
    path('get/users/autocomplete', AutocompleteUsersListView, name="get-autocomplete-users-list"),
]

PROJECT_NAME_HERE/apps/portal/urls.py
from django.urls import path
from .views import IndexView

app_name = "portal"

urlpatterns = [
    path("", IndexView, name="home")
]

PROJECT_NAME_HERE/templates/401.html
{% extends '_base.html' %}
{% block title %}401 | Not Authorized{% endblock %}
{% block page %}
      <div class="page-content">
        <div class="container text-center">
          <div class="display-1 text-muted mb-5"><i class="si si-exclamation"></i> Not Authorized (401)</div>
          <h1 class="h2 mb-3">Oops.. You just found an error page..</h1>
          <p class="h4 text-muted font-weight-normal mb-7">We are sorry but you are not authorized to access this page&hellip;</p>
          <a class="btn btn-primary" href="javascript:history.back()">
            <i class="fe fe-arrow-left mr-2"></i>Go back
          </a>
        </div>
      </div>
{% endblock %}

PROJECT_NAME_HERE/templates/503.html
{% extends '_base.html' %}

{% block title %}500 | Resource Temporary Unavailable{% endblock %}

{% block page %}
      <div class="page-content">
        <div class="container text-center">
          <div class="display-1 text-muted mb-5"><i class="si si-exclamation"></i> 503</div>
          <h1 class="h2 mb-3">Oops.. You just found an error page..</h1>
          <p class="h4 text-muted font-weight-normal mb-7">We are sorry but our service is currently not available&hellip;</p>
          <a class="btn btn-primary" href="javascript:history.back()">
            <i class="fe fe-arrow-left mr-2"></i>Go back
          </a>
        </div>
      </div>
{% endblock %}

PROJECT_NAME_HERE/templates/_base.html
{% load static %}
{% load recaptcha2 %}
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <link rel="icon" href="{% static 'assets/images/favicon.png' %}" type="image/x-icon"/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/favicon.png' %}" />
    <!-- Generated: 2018-04-16 09:29:05 +0200 -->
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'assets/css/dashboard.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/plugins/charts-c3/plugin.css' %}" rel="stylesheet" />
    <!-- <link href="{% static 'assets/plugins/maps-google/plugin.css' %}" rel="stylesheet" /> -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
    <link rel="stylesheet" href="{% static 'dashboard/css/dashboard.min.css' %}" />
    {% block header_css %}{% endblock %}
    
    <script src="{% static 'assets/js/require.min.js' %}"></script>
    <script>
      requirejs.config({
          baseUrl: '{% get_static_prefix %}'
      });
    </script>
    <script src="{% static 'assets/js/dashboard.js' %}"></script>
    
    {% block header_js %}{% endblock %}
  </head>
  <body class="">
    {% include 'preloader.html' %}
    {% if is_user_switched == 1 %}
    <div class="alert alert-warning fixed-bottom mb-0">You are currently working as a different user. <a href="{% url 'accounts:logoutas' %}">Click Here</a> to switch back.</div>
    {% endif %}
    <div class="page">
      {% block page %}{% endblock %}
    </div>

    {% include 'analytics.html' %}
    {% recaptcha_init %}

    <!-- c3.js Charts Plugin -->
    <!-- <script src="{% static 'assets/plugins/charts-c3/plugin.js' %}"></script> -->
    <!-- Google Maps Plugin -->
    
    <!-- <script src="{% static 'assets/plugins/maps-google/plugin.js' %}"></script> -->
    <!-- Input Mask Plugin -->
    <script src="{% static 'assets/plugins/input-mask/plugin.js' %}"></script>
    <script src="{% static 'dashboard/js/dashboard.min.js' %}"></script>
    {% block footer_js %}{% endblock %}
  </body>
</html>

PROJECT_NAME_HERE/templates/_success.html
<div class="row">
    <div class="col-12 col-md-8 mx-auto">
        <div class="text-center mb-6">
            <i class="fe fe-check-circle text-success" style="font-size:50px;"></i>
        </div>
        <div class="card">
            <div class="card-body p-6">
                <div class="card-title text-center font-weight-bold">All Done!</div>
                <p class="text-center">{{ message }}</p>
            </div>
        </div>
        <div class="text-center text-muted">
            <a class="btn btn-primary" href="{{ link|default:"javascript:history.back()" }}">
                <i class="fe fe-arrow-left mr-2"></i>{{ cta|default:"Go back" }}
            </a>
        </div>
    </div>
</div>

PROJECT_NAME_HERE/templates/analytics.html
{% if not meta.debug %}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-114825241-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'GA_ANALYTICS_ID_HERE', {
    'custom_map': {'dimension1': 'user'}
  });
  gtag('event', 'page_load', {'user': "{{ user.id }}"});

</script>

{% endif %}

PROJECT_NAME_HERE/templates/confirm-action.html
{% extends '_base.html' %}
{% block title %}Confirm Action{% endblock %}

{% block page %}
    <div class="page-single">
        <div class="container">
            <div class="row">
                <div class="col-8 mx-auto">
                    <div class="text-center mb-6">
                        <i class="fe fe-alert-triangle text-danger" style="font-size:50px;"></i>
                    </div>    
                    <form class="card" action="" method="post">
                        {% csrf_token %}
                        <div class="card-body p-6">
                            <div class="card-title text-center">Are you sure?</div>
                            <p class="font-weight-bold text-center">
                                Are you sure you want to {{ action }} with {{ key }} = {{ value }}. This will delete all data related to given {{ key }}.
                            </p>
                            <div class="form-footer">
                                <div class="row">
                                    <div class="col-12 col-md-6 p-3">
                                        <a href="javascript:history.back()" class="btn btn-primary btn-block">No</a>
                                    </div>
                                    <div class="col-12 col-md-6 p-3">
                                        <button type="submit" name="yes" class="btn btn-danger btn-block">Yes</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    
                        <div class="text-center text-muted text-danger">
                            {% if warning %}
                                <div class="alert alert-danger">{{ warning }}</div>
                            {% else %}
                                The Action cannot be undone.
                            {% endif %}
                        </div>
                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

PROJECT_NAME_HERE/templates/error.html
{% extends '_base.html' %}

{% block title %}You found an error page{% endblock %}

{% block page %}
<div class="page-single">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8 mx-auto">
                <div class="text-center mb-6">
                    <i class="fe fe-alert-triangle text-danger" style="font-size:50px;"></i>
                </div>
                <div class="card">
                    <div class="card-body p-6">
                        <div class="card-title text-center font-weight-bold">Oops</div>
                        <p class="text-center">An error occured while processing your request!</p>
                        <div class="text-secondary text-center">Technical Details: {{ error|default:"unknown" }}</div>
                    </div>        
                </div>
                <div class="text-center text-muted">
                    Contact Support for more info.
                    <div class="my-2">
                        <a class="btn btn-primary btn-sm" href="{% url 'dashboard:home' %}">
                            <i class="fe fe-arrow-left mr-2"></i>Go Home
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

PROJECT_NAME_HERE/templates/preloader.html
{% load static %}
<div id="preloader">
    <div class="background-wrapper">
        <div class="bg-left">
        </div>
        <div class="bg-right">
        </div>
    </div>
    <div class="wrapper">
        <div class="absolute-center text-center content">
            <img class="logo-med" src="{% static 'assets/images/logo.png' %}" />
            <div class="loader-progress">
                <div class="loader-bar"></div>
            </div>
        </div>
    </div>
</div>

PROJECT_NAME_HERE/templates/success.html
{% extends '_base.html' %}

{% block title %}Success{% endblock %}

{% block page %}
<div class="page-single">
    <div class="container">
        {% include '_success.html' %}
    </div>
</div>
{% endblock %}